<?php

use Illuminate\Database\Seeder;
use App\Models\Medicine;

class MedicineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Medicine::insert([
        //     ['name'=>'Tab innofol Hb'],['name'=>'Lefritas'],['name'=>'Tab Hb hope'],['name'=>'Tab Ferilife XY'],['name'=>'Tab Ravicap M'],['name'=>'Tab Ravicap-100'],['name'=>'Tab Mom Fe plus'],['name'=>'Tab Tonofolic XY'],['name'=>'Tab Livogen Z'],['name'=>'Tab Livogen'],['name'=>'Tab Dolibird'],['name'=>'Tab BD123'],['name'=>'Tab Folvite'],['name'=>'Tab Mylsta-D'],['name'=>'XTab R-folvite'],['name'=>'Tab Calom veg'],['name'=>'Tab Momcal'],['name'=>'Tab Molecal D3'],['name'=>'Tab Richkal'],['name'=>'Tab Dorcical Fizz'],['name'=>'TAb Caldison-500'],['name'=>'Protien Powder'],['name'=>'Tab Doximiom'],['name'=>'Tab M-well SR(200-400)'],['name'=>'Tab Posito SR(200,300,400)'],['name'=>'Tab Emprogest-SR(400)'],['name'=>'Tab PGyon-SR(200,300,400)'],['name'=>'Tab Vifogest(300)'],['name'=>'Tab R-focate plus'],['name'=>'Tab Natursure'],['name'=>'Tab Ecosprine(75,150)'],['name'=>'Tab Duphastone'],['name'=>'Tab Esvalsure(2mg)'],['name'=>'Tab Progynova(1)(2mg)'],['name'=>'Tab Estrabet(2ml)'],['name'=>'Tab Evtab(2mg)'],['name'=>'Tab Alihver'],['name'=>'Cap Gestus(400mg)'],['name'=>'Cap Gestobond(400mg)'],['name'=>'Cap Gufipro(400mg)'],['name'=>'Cap Strone(400mg)'],['name'=>'Cap Fsprogest(400mg)'],['name'=>'Cap natursure(400mg)'],['name'=>'Gel Elnprogest(0.8%)'],['name'=>'Gel Gestus(0.8%'] 
        // ]);

        Medicine::insert([
            // PROGESTERONE-400
            ['name'=>'CAP GESTUS-400'],
            ['name'=>'CAP GUFIPRO-400'],
            ['name'=>'EMPROGEST GEL 0.8%'],
            ['name'=>'GESTUS GEL 0.8%'],
            ['name'=>'CAP GESTOBOND-400'],
            ['name'=>'CAP STRONE-400'],
            ['name'=>'CAP FSPROGEST-400 MS'],
            ['name'=>'TAB EMPROGEST 300SR'],
            ['name'=>'TAB VITOGEST 300SR'],
            ['name'=>'TAB M-WELL 200SR'],
            ['name'=>'TAB POISITO SR'],
            ['name'=>'TAB NATUROSURE SR'],
            ['name'=>'TAB PGTON SR 300MG'],
            // ESTRADIOL
            ['name'=>'TAB EV'],
            ['name'=>'TAB ESVAL SURE'],
            ['name'=>'TAB PROGYNOVA 1MG'],
            ['name'=>'TAB PROGYNOVA 2 MG'],
            ['name'=>'TAB ESTRABET'],
            // CALEIUM
            ['name'=>'TAB CALOM VEG'],
            ['name'=>'TAB MOMCAL'],
            ['name'=>'TAB RICHKAL 500'],
            ['name'=>'TAB MOLECAL D3'],
            ['name'=>'TAB CALDISON 500'],
            ['name'=>'SUP CALCIP'],
            ['name'=>'DORCICAP FIZZ'],
            ['name'=>'TAB CORCIUM'],
            // IRON
            ['name'=>'TAB HB-HOPE'],
            ['name'=>'CAP-LE-FERRITAS'],
            ['name'=>'TAB FERILIFE'],
            ['name'=>'TAB MOM-FE PLUS'],
            ['name'=>'CAP LEVOGEN'],
            ['name'=>'TAB-RERICAP M'],
            ['name'=>'TAB RERICAP'],
            ['name'=>'TAB INNOVOFOL HB'],
            ['name'=>'TAB TONOFOLIC'],
            ['name'=>'HB-HOPE SYP'],
            // VITA-D
            ['name'=>'VITACET D3 SUCHET'],
            ['name'=>'CALOM D3 SUCHET'],
            ['name'=>'VITANEO D3 LIQUID'],
            // PROTEIN POWDER -->1-3 MONTH NORMAL ANC 
            ['name'=>'TAB DOXIMOM-OD'],
            ['name'=>'TAB MYLSTA-D'],
            ['name'=>'TAB R- FOLVITE'],
            ['name'=>'TAB ECOSPRINE 150'],
            ['name'=>'TAB ECOSPRNE 75'],
            ['name'=>'ALIVHER-SILDENATIL'],
            ['name'=>'TAB SILDAPREP'],
            ['name'=>'TAB SUHAGRA'],
            ['name'=>'INJ HCG-5000'],
            ['name'=>'TAB DUPHASTONE (10 MG)'],
            // VOMITTING
            ['name'=>'TAB VOMIMOM-MD'],
            ['name'=>'TAB GRENI- MD'],
            ['name'=>'EMESET 2 MG'],
            ['name'=>'EMESET 5 MG'],
            // ACIDITY
            ['name'=>'CAP HAPPI-D'],
            ['name'=>'CAP RABIMOM DSR'],
            ['name'=>'CAP RABICAL D'],
            ['name'=>'PANSEC D5'],
            ['name'=>'TAB PANTACUI'],
            ['name'=>'MUCAIN GEL'],
            ['name'=>'NUGICIDE GEL'],
            ['name'=>'SUP RABICUL'],
            ['name'=>'TAB PAN-D'],
            ['name'=>'SUP DIAGENE'],
            // ANTIBIOTIC
            ['name'=>'TAB INFLACET TBR'],
            ['name'=>'TAB AZEE-250'],
            ['name'=>'TAB AZEE-500'],
            ['name'=>'TAB DCMOL-H'],
            ['name'=>'TAB CEFILUU-200'],
            ['name'=>'CAP ZIFI-CU-200'],
            ['name'=>'TAB ZIFI-250'],
            ['name'=>'TAB ZIFI-50'],
            ['name'=>'TAB ZEFURO-250'],
            ['name'=>'TAB ZEFURO-500'],
            ['name'=>'TAB ZEFU-200'],
            ['name'=>'AMOXICLAVE-625'],
            ['name'=>'AUGMENTIN-625'],
            ['name'=>'TAB MOXIGOLD-CU'],
            // COLD COUGH
            ['name'=>'TAB WIKORY'],
            ['name'=>'TAB L-DIO-1'],
            ['name'=>'TAB L- DIO'],
            ['name'=>'TAB DIAMINIC DCA'],
            ['name'=>'SUP MEDIREST DX'],
            ['name'=>'SUP TUS-QDX'],
            ['name'=>'DMR 30'],
            ['name'=>'TAB DCMOL-M'],
            // DRY CEUGH
            ['name'=>'MEDIREST EXPEC'],
            ['name'=>'TAB AZEE 250'],
            ['name'=>'TAB AZEE 500'],
            ['name'=>'SUP GRILINTUS'],
            ['name'=>'SUP MOMCOFF-D'],
            ['name'=>'SUP RUDRAX'],
            ['name'=>'SUP COTEX'],
            ['name'=>'OFLOX OZ'],
            ['name'=>'OFLOY OZ'],
            ['name'=>'FLOXUM 500'],
            ['name'=>'LEVOFLOX 500'],
            ['name'=>'LEVOFLOX 250'],
            ['name'=>'METROGYL 1.4'],
            ['name'=>'TAB METROGYL'],
            // CONSTIPUTION
            ['name'=>'SUP LMH PLUSE'],
            ['name'=>'PWDER PROCTOBULK'],
            ['name'=>'SUP CREMAFFIN'],
            ['name'=>'SUP CREMAFFIN PLUS'],
            ['name'=>'TAB DULCOLAX'],
            // PAIN KILLER
            ['name'=>'TAB DOLO 650'],
            ['name'=>'TAB MEFTAL SPAS'],
            ['name'=>'TAB MEFSON'],
            ['name'=>'TAB INFLASET SP'],
            ['name'=>'TAB BIOZOBID PLUS'],
            ['name'=>'TAB CYCLO PAM'],
            ['name'=>'TAB DNA P'],
            ['name'=>'TAB DNA SR'],
            ['name'=>'TAB NEPROCIN'],
            ['name'=>'TAB COMBIFIAM'],
            ['name'=>'TAB BUSCOGAST'],
            ['name'=>'TAB DNA-MR'],
            // DIARRHOEA
            ['name'=>'TAB SPORLAC DS'],
            ['name'=>'SPORLAC PWDR'],
            ['name'=>'OFLOX-OZ'],
            ['name'=>'TAB METROGYL'],
            ['name'=>'ORS POWDER'],
            // VERTIGO
            ['name'=>'TAB VERTIN 0.8 MG'],
            ['name'=>'TAB VERTIN 0.4 MG'],
            ['name'=>'TAB STEMATIL MD'],
            // BACK PAIN
            ['name'=>'VOLINI GEL'],
            // STRECH MARK
            ['name'=>'RICH GLOW CREAM'],
            ['name'=>'LUCIARU CREAM'],
            ['name'=>'MEDIMOIST CREAM'],
            // URINE
            ['name'=>'SYP URICITRAL'],
            ['name'=>'SYP CITRALKA'],
            ['name'=>'LEVOFLOX 1000'],
            ['name'=>'LEVOFLOX 500'],
            ['name'=>'TAB URITAST'],
            ['name'=>'TAB HYOSIMEX'],
            ['name'=>'TAB HYOSIMAX'],
            ['name'=>'TAB URIVOID'],
            ['name'=>'ALPRAX-0.25MG'],
            ['name'=>'ALPRAX-0.05MG'],
            ['name'=>'TAB AUIL'],
            ['name'=>'TAB DEXONA'],
            ['name'=>'TAB CLONAZEPAM 0.25'],
            // INJ
            ['name'=>'T.T'],
            ['name'=>'INJ STRONE 100'],
            ['name'=>'INJ PRO 9'],
            ['name'=>'INJ GESTOFIT'],
            ['name'=>'INJ GUFIGEST'],
            ['name'=>'INJ AQUAGEST'],
            ['name'=>'INJ BETNAZOL'],
            ['name'=>'INJ HCG 5,000'],
            ['name'=>'INJ OMNIKACIN 500'],
            ['name'=>'INJ OMNIKACIN 250'],
            ['name'=>'INJ OMNIKACIN 750'],
            ['name'=>'INJ OMNIKACIN 100'],
            ['name'=>'INJ EMESET'],
            ['name'=>'INJ RENTEC'],
            ['name'=>'INJ OMEZ'],
            ['name'=>'INJ PANTACUL 40'],
            ['name'=>'INJ CONTRAMOL'],
            ['name'=>'INJ DYNATROY'],
            ['name'=>'INJ GRENICETRONE'],
            ['name'=>'INJ P.C.M (J.V)'],
            ['name'=>'INJ P.C.M (J.V)'],
            ['name'=>'INJ OFRAMEX FORT'],
            ['name'=>'INJ MONOCET 2 gm'],
            ['name'=>'INJ CEFTRASUN 1 gm'],
            ['name'=>'INJ ZOSTUM 3 gm'],
            ['name'=>'INJ ZOSTUM 2 gm'],
            ['name'=>'INJ ZOSTUM 1.5 gm'],
            ['name'=>'INJ ADUENT 1.2 gm'],
            ['name'=>'INJ AUGMENTINE 1.2 gm'],
            ['name'=>'INJ PIPZO 4.5 gm'],
            ['name'=>'INJ PIPZO 2.25 gm'],
            ['name'=>'INJ PIPZO 1.125 gm'],
            // WHITE DISCHARGE VAGINAL
            ['name'=>'CUP CAnDID-CL'],
            ['name'=>'CUP VAGIMoM-v'],
            ['name'=>'CUP CLID-CL'],
            ['name'=>'CUP FENZA'],
            ['name'=>'CUP FIVAOSA'],
            ['name'=>'CANDIDERMA CREAM'],
            ['name'=>'ONABET CREA'],
            ['name'=>'CANDID CL GEL'],
            ['name'=>'SERTADOL CREAM'],
            ['name'=>'CANDID B CREAM'],
            ['name'=>'FIVASA CREAM'],
            ['name'=>'TAB DOXICYECLINE'],
            ['name'=>'TAB METROGYL'],
            ['name'=>'TAB ZOCON'],
            ['name'=>'TAB IRANSUM 200'],
            ['name'=>'INJ LEVOFLOX 500'],
            ['name'=>'INJ OFIOX 2 MG'],
            ['name'=>'INJ M.V.I'],
            ['name'=>'INJ OROFOR'],
            ['name'=>'INJ IRON-SUCROSE'],
            ['name'=>'NS 100ML'],
            ['name'=>'NS 500ML'],
            ['name'=>'NS 1 LIT'],
            ['name'=>'RL 500'],
            ['name'=>'RL 1 LIT'],
            ['name'=>'DNS 500'],
            ['name'=>'DNS 1 LIT'],
            ['name'=>'5D 500ML'],
            ['name'=>'5D 1 LIT'],
            ['name'=>'10D 500ML'],
            ['name'=>'IV SET'],
            ['name'=>'VEIN FLOW 20'],
            ['name'=>'VEIN FLOW 22'],
            ['name'=>'SURGI FIX'],
            ['name'=>'SYR 2 CC'],
            ['name'=>'SYR 5CC'],
            ['name'=>'SYR 10CC'],
            ['name'=>'SCALP VEIN']
            
        ]);
    }
}
