stages:
  - deploy
deploy:
  stage: deploy
  script:
    - cd /var/www/html
    - rsync -av --exclude=/var/www/candor/jamyNeZZ/0/unikwork/candorivf-web/* /var/www/candor/jamyNeZZ/0/unikwork/candorivf-web/* /var/www/html/
    - php artisan config:clear
    - php artisan config:cache
    - php artisan view:clear
