stages:
  - deploy
deploy:
  stage: deploy
  script:
    - cd /var/www/html
    - sudo cp /var/www/candor/jamyNeZZ/0/unikwork/candorivf-web/app/* /var/www/html/app/
    - sudo cp /var/www/candor/jamyNeZZ/0/unikwork/candorivf-web/assets/* /var/www/html/assets/
    - sudo cp /var/www/candor/jamyNeZZ/0/unikwork/candorivf-web/database/* /var/www/html/database/
    - sudo cp /var/www/candor/jamyNeZZ/0/unikwork/candorivf-web/resources/* /var/www/html/resources/
    - sudo cp /var/www/candor/jamyNeZZ/0/unikwork/candorivf-web/routes/* /var/www/html/routes/
    - sudo cp /var/www/candor/jamyNeZZ/0/unikwork/candorivf-web/storage/* /var/www/html/storage/
    - php artisan config:clear
    - php artisan config:cache
    - php artisan view:clear