@extends('Apphtml.Trimster.main')
@section('title', 'What to Expect')
@section('content')

  <div class="container">
    <div class="main" id="main">
      <h4>What Is the First Trimester of Pregnancy?</h4>
      <p>The first trimester is the first phase of pregnancy. It starts on the first day of your last period -- before you’re even actually pregnant -- and lasts until the end of the 13th week. It’s a time of great anticipation and of rapid changes for both you and your baby. Knowing what to expect will help you get ready for the months ahead.</p>
      <h4>First Trimester Changes in Your Body</h4>
      <p>Pregnancy is different for every woman. Some women glow as gliter with good health during this first 3 months; others feel absolutely miserable and sick. Here are some of the changes you might notice, what they mean, and which signs warrant a call to your doctor.</p>
      <p>Bleeding. About 25% of pregnant women have slight bleeding during their first trimester. Early in the pregnancy, light spotting may be a sign that the fertilized embryo has implanted in your uterus. But if you have severe bleeding, cramping, or sharp pain in your belly, call the doctor. These could be signs of a miscarriage or ectopic pregnancy (a pregnancy in which  implantation is outside the uterus).</p>
      <p>Breast tenderness. Painful breasts are one of the earliest signs of pregnancy. They're triggered by hormonal changes, which are getting your milk ducts ready to feed your baby. Your breasts will probably become tender  throughout the first trimester. Going up a bra size (or more) and wearing a support bra can make you feel more comfortable. You probably won’t go back to your regular bra size until after your baby is finished nursing.</p>
      <p>Constipation. During pregnancy, high levels of  progesterone slow down the peristalsis that normally move food through your system. Add to that the extra iron you're getting from your prenatal vitamin, and the result is uncomfortable constipation and gas that can keep you feeling bloated throughout your pregnancy. Eat more fiber and drink extra fluids to keep things moving more smoothly. Physical activity can also help.</p>
      <p>If your constipation is really bothering you, talk to your doctor about what mild laxative or stool softeners are safe to use during pregnancy.</p>
      <p>Discharge. It's normal to see a thin, milky white discharge (called leukorrhea) early in your pregnancy. You can wear a panty liner if it makes you feel more comfortable, but don't use a tampon because it could put germs into your vagina. If the discharge smells really bad, if it’s green or yellow, or if there's a lot of clear discharge, call the doctor as it may bee because of infection.</p>
      <p>Fatigue. Your body is working hard to support a growing baby. That means you’ll get tired more easily than usual. Take naps or rest when you need to during the day. Make sure you're getting enough iron. Too little can lead to anemia, which can make you even more tired.</p>
      <p>Food likes and dislikes. Although you may want to eat something sour like lemon or “kachi keri”, as the old stereotype goes, your tastes can change while you're pregnant. More than 60% of pregnant women have food cravings. More than half have foods they really don’t like. Giving in to cravings from time to time is OK, so long as you eat healthy, low-calorie foods most of the time. The exception is pica -- a craving for nonfoods like clay, dirt, and laundry starch, which can be dangerous for you and your baby. If you experience this kind of craving, report it to your doctor right away.</p>
      <p>Peeing a lot. Your baby is still pretty small, but your uterus is growing and it's putting pressure on your bladder. As a result, you may feel like you have to go to the bathroom all the time. Don't stop drinking fluids -- your body needs them -- but do cut down on caffeine (which stimulates your bladder), especially before bedtime. When nature calls, answer it as soon as you can. Don't hold it in.</p>
      <p>Heartburn. During pregnancy, your body produces more of  progesterone. It relaxes smooth muscles, like the ring of muscle in your lower esophagus, the tube that connects your mouth and stomach. These muscles normally keep food and acids down in your stomach. When they loosen up, you can get acid reflux, otherwise known as heartburn. To avoid the burn:</p>

      <ul><li>Eat small frequent meals.</li></ul>
      <ul><li>Don't lie down right after you eat and walk a bit.</li></ul>
      <ul><li>Avoid greasy, spicy, and acidic foods (like citrus fruits).</li></ul>
      <ul><li>Try raising your pillows so that u in reclining position when you sleep.</li></ul>

      <p>Mood swings. Increased fatigue and changing hormones can put you on an emotional roller coaster that takes you from joyous to miserable, or from hopeful to terrified in a matter of seconds. It's OK to cry, but if you feel overwhelmed, try to find an understanding ear. You can talk to your partner, a friend, a family member, or even a professional.feeling the extremes of emotion is normal during this phase.</p>
      <p>Morning sickness. Nausea is one of the most common symptoms. Up to 85% of pregnant women have it. For some pregnant women, nausea is mild. Others can't start their day without vomiting. Nausea is usually worse in the morning (hence the name, "morning sickness"). To calm your nausea, try eating small, bland, or high-protein snacks (toast, biscuit, banana, dry fruits and nuts or cheese) and sipping water, clear fruit juice (apple juice), or ginger mukhwas. You may want to even do this before you get out of bed. Avoid any foods that make you sick to your stomach. Nausea itself isn't anything to worry about, but if it’s severe or just won’t go away, it can affect the amount of nutrition your baby gets. Call your doctor if you can't stop throwing up or can't keep down any food.</p>
      <p>Weight gain. Pregnancy is one of the few times in a woman's life when weight gain is considered a good thing, but don't overdo it. During the first trimester, you might just gain a kg or two (your doctor may suggest you adjust your weight gain up or down if you started your pregnancy underweight or overweight). Although you're carrying an extra person, you really aren’t eating for two. You only need about an extra 150 calories a day during the first trimester. Get those calories the healthy way, by adding extra fruits and vegetables, milk, whole-grains, pulses to your diet.</p>
    </div>
  </div>

@endsection
