@extends('Apphtml.Trimster.main')
@section('title', 'Weeks 21-25')
@section('content')
	<center>
      <div class="button-box">
	  	<!-- <div id="btn"></div> -->
        <button type="button" style="background-color:#FFFFFF; " class="toggle-btn button-box1" id="week11" onclick="week1()"><b>21</b></button>
        <button type="button" style="background-color:#40BECC; " class="toggle-btn button-box2" id="week12" onclick="week2()"><b>22</b></button>
        <button type="button" style="background-color:#40BECC; " class="toggle-btn button-box2" id="week13" onclick="week3()"><b>23</b></button>
        <button type="button" style="background-color:#40BECC; " class="toggle-btn button-box2" id="week14" onclick="week4()"><b>24</b></button>
        <button type="button" style="background-color:#40BECC; " class="toggle-btn button-box2" id="week15" onclick="week5()"><b>25</b></button>
  	  </div>
    </center>
  <div class="container">
      <div id="w1">
      </div>
        <h4>Week 21</h4>
        <p><b>Baby : </b>The baby's skin resembles like that of an adult now having the four layers. Also the subcutaneous fat is deposited around neck, shoulders, kidneys and spine. This subcutaneous fat will be accountable for 5% of babies weight at birth. The brown fat is very much needed for baby after birth to regulate the temperature of the body.</p>
        <p>This week, your baby is making more sense of the world and developed her sense of touch. In fact your little one's grip is quite strong now, and since there is nothing else to grab in uterus. She may sometimes hold on tight to that umbilical cord. Don't worry- it's tough enough to handle it. The sense of sight is also becoming more fine-tuned your foetus can now perceive light and dark much better than before even with those fused eyelids, but remember unless you are shining a flashlight over your belly, which you can do, by the way, it will be mostly dark for your kids inside inside that cozy womb of yours.</p>
        <p>She can also hear your voice, your heart beat, gurgling stomach and whoosh whoosh of blood circulating through your body.</p>
        <p>The foetus endocrine glands are working at a full speed and the immune system is fully developed. From this week it will be joined by spleen which will produce white blood cells (leukocytes) and antibodies which will filter bacteria, protozoa and foreign bodies. leukocytes in blood will help fight off infections.</p>
        <p>During night when the foetus is more active you can try coming then buy by soothing words, soft music and lullabies.</p>
        <p><b>Mom : </b>At 21 weeks pregnant your baby might be starting to leave his mark in the form of stretch marks that is all over your stomach, butt, thighs, hips and breasts. This pink, red, purple, redish brown or dark brown streaks appear as your body expands and your tummy and breast just keep on growing, the supporting tissue under your skin gets torned and the skin stretches. Estimates vary, but at least one in two women get them, though you are likely candidate if your mom had stretch marks during her pregnancy. Rapid weight gain can also predispose you to getting stretch marks another good reason to add your pounds slowly and steadily at an average of about a pound a week these days. Depending on your complexion and the jeans you inherited, this lines first show up as red, pink or brown streaks and with time will eventually fade.</p>
        <p>Now that you are starting to look pregnant- and not just like you eat a particularly larger lunch- and those kids can no longer be mistaken for gas the reality of pregnancy is probably beginning to sink in.</p>
        <p>And with it, visit you may find, a few ambivalent or anxious feelings your even ambivalent about admitting: me, a mom?. At some point in pregnancy and usually once that pregnancy becomes a very visible reality just about every expectant mother and father begins to feel anxiety and fear almost as if you are on a runway train and there is an enormous changes coming around the bend.</p>
        <p>And not only is it completely normal to feel anxious , it's especially healthy to acknowledge it. Talk your feelings over with your friends who have had babies, they will reassure you. Most important discuss your fears with your partner's who is probably just as in need of a good heart to heart.</p>

        <p><b>Tips</b></p>
        <p><b>Raise your feet : </b>Your shoes might not be fitting you as your ankles and feet are swollen. Because your body is about 50% more blood and fluid than it did pre baby this body parts mein spell so be sure to  elevate your legs while your sit.</p>
        <p><b>Watch your weight : </b>How much weight is too much? That all depends ask your practitioner the target weight gain and then gain weight accordingly. being too plumpy or gaining access amount of weight is not good at all for you and for your baby.</p>
        <p><b>Exercise : </b>You should exercise but keep it low impact with yoga, walking or swimming. You are more susceptible to injury right now thanks to ligament loosening relaxin in your body.</p>
        <p><b>Avoid empty calories : </b>The emphasis is on "useless" (aka- empty)-you still want to eat enough of the right kinds of calories to keep your baby fed and growing. After all the idea is not to lose weight. Losing weight is always a bad idea when you are pregnant but to slow the rate at which you are gaining. Easy, nutritious ,calorie reducing strategy strategies like substituting fresh fruit for dried baked potatoes or yams for French French fries can make a big difference.</p>
        <p><b>Walk 30 minutes : </b>Both during pregnancy and in those first postpartum weeks physical activity is one of the best ways to stimulate your bowels and fight constipation. Even just half hour walk a day can do the trick especially if you drink plenty of water and favour fibre rich foods just remember to take some trail mix when you hit the trail.</p>
        <p><b>Hair removal : </b>Use a plucker or a razor to shave an area with unwanted hairs. If your skin is not so sensitive you can go for waxing too but no laser, electrolysis ,depilatories and bleaching.</p>

  	 	<div id="w2">
      </div>
  	 		<h4>Week 22</h4>
  	 		<p><b>Baby : </b>the brain's intensive growth slows down. brain has enough neurones now to last for the entire life. the baby's brain is about hundred grams and there are grooves and wrinkles in it. the babies curious and now investigates is feelings and tactile sensations. The baby now touches his face, body, umbilical cord and starts making faces, stretches its legs up to the face and occasionally taps on the uterine wall. The movements are becoming more willful and complex. </p>
  	 		<p>The babies skeletal system and bones now strengthen.  The baby's body proportion is  changing now. The arms and legs of the foetus are growing at a greater speed as compared to the head. The heart is also growing. It now pumps up to 30 litres a day. </p>
  	 		<p>the liver is also able to separate the toxins and expel them across the placenta. The uterus is now roomyvand the baby is able to twist, dance, turn and flip flop in the uterus. Ok now really count on the frequencies of his moments.</p>
  	 		<p>The sense of sight is also becoming more fine-tuned. The foetus can  now perceive light and dark much better than before, even with those fused eyelids.</p>
  	 		<p><b>Mother : </b>22 weeks is a great time to enjoy pregnancy. You can feel your baby wing around which will provide you a sense of joy, tranquility and optimism. Your baby is getting pretty big nowadays but don't worry it won't be that uncomfortable. but your tummy is not the only thing that's growing these days have you looked down at your feet quick look now before you can't see them anymore if you are like many expected women you will discover that feat gets bigger too.</p>
  	 		<p>While some foot growth can be attributed to pregnancy swelling, there's another reason that feet increases in size during pregnancy and sometimes don't shrink back afterward. Remember relaxin, that pregnancy hormones that loosens ligament and joints around your pelvis so your baby can fit through ? well it doesn't discriminate between the ligaments  you would want lossened up,  like those pelvic ones, and those you would rather just leave alone, like the ones in your feet.</p>
  	 		<p>your weight is gradually increasing week by week average weight gain will be approximately 5 to 7 kgs. You may start feeling Braxton Hicks contractions now, these are the practice contractions which uterus practices since conception but you may start feeling them now, they are irregular in their nature.</p>
  	 		<p><b>Tips</b></p>
  	 		<p><b>Braxton Hicks contractions : </b>Is here you transparencing for delivery? if you feel irregular, painless ,squeezing sensations in your abdomen. it is  Braxton Hicks contractions and are not dangerous. they are bit like a dress rehearsal. Keep in mind that while they can be hard to distinguish from the real thing they are not efficient enough to push your baby out the way.</p>
  	 		<p><b>Magnesium supplement : </b>In addition to strengthening babies bones and teeth, magnesium works to stimulate enzyme function, regulate insulin and control blood sugar levels. If you are deficient in magnesium you may feel fatigued and lack muscle strength or have like cramps or restless legs. other severe consequences can include poor fetal growth or pre eclampsia. Ask your doctor if you should add a magnation supplement to your diet.</p>
  	 		<p><b>Fit in work : </b>Scientific research shows that you are not only the one who benefits from pregnancy exercise apparently babies of mom's who exercise throughout pregnancy score higher on average and general intelligence test by age 4. Not only will your workout boost your muscle power,but it will also boost your baby's brain power!</p>
  	 		<p><b>Take breath : </b>now's a great time to learn some soothing relaxation exercise not just because they can help you cope with pregnancy worries but because they will come in handy in your life as a new mom.  Yoga is a fabulous distressor, but here is a technique you can use just about anywhere, anytime to soothe your soul. Sit with your eyes closed and imagine a beautiful peaceful scene (maybe a sunset over your favourite beach  or serene mountain ) then working your way up from your toes to your face, concentrate on relaxing every muscle of your body. Slowly and  deeply breathe only through your nose and choose a simple word to repeat a loud every time you exhale. 10 minutes should do the trick. Doing even a minute or two is better than nothing.</p>

  	 	<div id="w3">
      </div>

  	 		<h4>Week 23 </h4>
  	 		<p><b>Baby : </b>Your baby is around 11 inches long and just 500 to 700 grams in weight, for baby should double his weight over the next four weeks alone and you may feel as though you do, too. His skin is bit wrinkled since it grows a lot faster than fat but soon he will start to fit his frame as fat deposits fill the things out. And although at 23 weeks pregnant your baby's organs and bones are visible through the skin will become less transparent once those fat deposits settle in.</p>
  	 		<p>You have probably heard your developing baby's heartbeat through a Doppler and number of times already, though you never get tired of hearing it, but by now you or your doctor might also be able to hear it through a standard stethoscope. what a hearttrob!</p>
  	 		<p>the lungs are not yet ready to breathe outside the womb but they are developing  at  fast pace. The baby completes an action of 60 breaths per minute inside the womb. The lung maturity and structural development is running at a greatest speed because the circulatory system is now dwelling inside the lungs and giving proper blood supply till the alveoli down there. The alveoli's structural development starts to get complete and it starts secreting some amount of surfactant. Surfactant is a soapy substance secreted by alveolar cells that is a must for lungs to breath. Without surfactant any one of us individual wont be  able to survive. </p>
  	 		<p>scientists believe that at 23 weeks of pregnancy, the baby starts to dream because it develops in REM sleep. In this sleep the baby opens eyes or becomes awake for few seconds in one hour and then goes back to sleep again.</p>
  	 		<p><b>Mother : </b>The baby's brain is developing now and the oxygen is ultimate supply for its brains development. To ensure the good development of your fetal brain you must have an hour or so of gentle walk in open air. </p>
  	 		<p>So try talking to your baby as much as possible because the baby will start recognising your voice and voices of the people around you. You may feel a sharp kick or active moment if there is a sudden loud noise. Avoid listening to harsh, rock and fast track sounds.</p>
  	 		<p>Babies immune system is aggressively working now. The baby is almost never exposed to bacterias and viruses from others blood because it is protected by a unit known as placenta which filters the harmful toxins and organisms and never allows baby to get infected but there are chances that if the infection is serious the baby might get infected. So it is very necessary for a mother to prevent her from any communicable diseases during her pregnancy as much as possible.</p>
  	 		<p>At 23 weeks pregnant your mind is fussy and your feet are growing. The palms of your hands and soles of your feet might be red and you might be more prone to heat rash and skin tags. stretch marks are blooming in vibrant shades of pink, red,  purple, redish brown or dark brown on pretty much every available surface of skin and wait what's that dark line running down the center of your belly? it's called Linea nigra a common emblem of pregnancy that maybe more noticeable in dark skin women. The linea nigra runs between your belly button and your pubic area. It's caused by the same pregnancy hormones responsible for all the skin discolorations you might be seeing like the darker shades of your areola and deeper tone of the freckles on your arms and legs.  Some women  usually those with darker skin notice discoloration on face too especially in the area around the nose, forehead, cheeks and eyes. It's called the mask of pregnancy because it appears as a mask line configuration on the face.</p>
  	 		<p>All this skin changes will fade within a few months after delivery. In the mean time bring on the concealer do not use the bleaching creams which would work anyway.</p>
  	 		<p><b>Tips</b></p>
  	 		<p><b>Oral hygiene</b></p>
  	 		<p>It is wrongly said that a mother loses its calcium because the baby utilizes the calcium from mothers teeth and cause dental caries the actual reason behind increased dental caries during pregnancy is hormonal shift, vomiting, nausea, morning sickness and poor oral hygiene. Morning sickness, dietary changes and vomiting causes pH imbalance in mouth demineralizes  the teeth and causes dental carries. You can take care of your dental cavities by doing twice a daily fluoride toothpaste using floss and mouth wash.</p>
  	 		<p><b>Get proper sleep : </b>It can be almost as hard to get a good night's sleep when you are pregnant as it is when you are new parent. With all that is going on in your body - your brain - its no wonder that a full night's rest can be so elusive. If you find it hard to get comfortable try sliding a pillow between your legs and resting with your knees bent.</p>
  	 		<p><b>Be hydrated : </b>Keep bottle of water by your side at all times. Staying hydrated helps maintain your additional blood volume, renews amniotic fluid and voices milk production. Though it really varies  based on your body type and size, how active you are and so on. The general rule of thumb is somewhere between 8 to 10 glasses of water a day from all sources, but be sure to talk to  your practitioner about what works for you and your situation.</p>
  	 		<p><b>Prevent urinary tract infections : </b>Now that it's being pushed by your growing uterus, your bladder makes the perfect breeding ground for bacteria and that can lead to urinary tract infection. Luckily there's a number of ways you can reduce your chance of developing a UTI during pregnancy. Drink plenty of water and cranberry juice, ideally  that doesn't contain sugar. Check out your urine colour - if it's dark not straw coloured, you are not getting enough fluids and could be setting yourself up for UTI. Don't hold it in pee as soon as you feel the earth and can find a bathroom. Concentrate on completely empting your bladder, when you urinate and try leaning forward when you feel to pee. wipe your front to rear after you use the toilet. Clean your genitals and the area surrounding them particularly after having sex. Wear all cotton undergarments and takes showers rather than baths whenever possible.</p>
  	 	
  		<div id="w4"> 
      </div>

			<h4>Week 24</h4>
			<p><b>Baby : </b>By 24 weeks, the 7th month, the baby is experiencing sleep and wake cycles. For about 6 to 9 hours a day, the baby is really into an active mood. Baby will tilts his head, raises eyebrows and would kick around, would try to feel everything the baby can feel and touch . This helps for his mental development.</p>
			<p>the growth rate of foetus is accelerated as the foetus is producing his own growth hormone.</p>
			<p>development of lung is now at its fullest the alveoli are now whining and are starting to produce the surfactant. This effect is the vital thing to help your baby breathe comfortably when his born right now, the lungs are very immature to breathe on its own. </p>
			<p>The baby Taj making facial expressions like yawning, frowing,  smiling, sucking. the baby will try exercising facial muscles.</p>
			<p>The baby even start responding by sudden jerks to  light or sound and even to mother's emotions.</p>
			<p>the baby skin is still red and little wrinkly. Yhe oil glands and sweat glands has now started developing. a little later subcutaneous layer of fat will accumulated just beneath the skin making it more smoother and more elastic.</p>

			<p><b>Mother : </b>This is the time when a mother will notice sudden shoot in her appetite. Her body will get more than before. your weight increases by 300 to 500 grams every week. Average total weight gain since the start of pregnancy would be 7 kgs. If your weight gain is going ahead, then your doctor adviced to start incorporating some physical exercise that is not harmful to the foetus. Avoid doing lunges, jumps and kicks  but you can do a modest amount of walking and little stretching if that's advisable. overweight causes a problem in the labour so you should try maintaining yourself in the shape as much as possible. Prenatal yoga, fresh air walks and swimming are best for you as of now.</p>
			<p>Your belly button will be pushed outwards because of your enlarging uterus will push anything that is coming in its way. This should get normal after the delivery, though the belly button and the skin of tummy might look a little stretched out but you can take it as a badge of honor that only moms get to wear.</p>
			<p>Carpal tunnel syndrome will be aggravated during pregnancy because in pregnancy there is increased in fluid in your body and this is mostly accumulated in lower extremities during the daytime, when you sleep this fluid is redistributed to other parts of your body especially at the level of wrist which will cause the compression of nerve and may cause tingling and numbness. the best way to avoid it is sleeping with your hands lying over a pillow. If you are doing repeated exercise is like playing piano or typing you should take a little bit of rest from doing so.</p>

			<p><b>Tips</b></p>
			<p><b>glucose screening : </b>Between 24 to 28 weeks of your pregnancy your consultant may advise you to test for glucose screening. It is sometimes known as oral glucose tolerance test, it is done to diagnose whether you have gestational diabetes, a temporary condition related with pregnancy or not. As diabetes have serious harmful effects on foetus, it is better to get screened. You are at increased risk of having gestational diabetes if you are overweight, have more amount of abdominal fat or are having a family history of diabetes.</p>
			<p><b>shower : </b>As you might be suffering from dry skin, it is better to take short showers- with use of lukewarm water, not very hot water or cold water with mild cleanser. You can definitely put any moisture riser after your bath.</p>
			<p><b>eat plenty of proteins : </b>Proteins are made up of amino acids which are building blocks of every cell of your baby's body to make it more adorable and more functional. The brain indeed needs protein for better functioning of your babies walk, talk, smile and various activities. During pregnancy you need at least 3 servings of proteins that is 75 grams of protein everyday. Most of the people achieve this goal but if you are a vegan or vegetarian diet it might be a little difficult for you to reach this. To compensate this you may end up eating one cup full of sprouted beans.</p>
			<p><b>keep a track of weight gain : </b>Ideal weight gain during pregnancy is 9 to 12 KG of your pre pregnancy weight but your doctor will advise you the target of weight gain depending upon your pre pregnancy weight your BMI and your family histories of diabetes and hypertension. By now you should be gaining at least 1 kg a month, if you are not gaining weight then there are chances of preterm delivery or IUGR to your baby. now the doctors will themselves keep a count of your weight gain and would advise you to either increase, maintain or slightly reduce your weight depending upon your obesity and nourishment.</p>

		<div id="w5"> 
    </div>
      
			<h4>Week 25</h4>
			<p><b>Baby : </b>By the 25th week of pregnancy the baby's face is already formed. The features are more humanly now and with the help of sonography and little imagination you can decide whether the baby looks like mum , dad or grandma or grandpa. The external ears continue to develop.</p>
			<p>The baby's muscles start to develop and each muscle takes its own responsibility for various functions. The reproductive system is now developing in its fullest. In boys the testicles that are formed will start descending from abdomen into scrotum whereas in females the vagina is still completing its process of development.</p>
			<p>Development of baby's bones is now started the baby is getting into a shape of calcified skeleton. Bones are still soft and cartilaginous. this is the time when mother requires  to have proper calcium intake so that it helps in development of baby's skeletal system.</p>
			<p>The bone marrow now starts participating in the blood formation. by now the responsibility of blood formation was on liver and spleen, by 5 weeks of pregnancy the blood formation is carried forward by liver but now slowly the bone marrow will take over the function.</p>
			<p>Baby's skin colour is becoming pink now because of the small blood vessels called capillaries are forming under the skin and filling with blood.By 25 weeks pregnant lungs are still very much works- in -progress. Do they are already beginning to produce surfactant a substance that will help them expand with oxygen after baby is born, the lungs are still too undeveloped to sufficiently send oxygen to the bloodstream and release carbon dioxide when the baby exhales.</p>
			<p>The lungs aren't the only system that's maturing for Air intake. Your baby's nostrils and nose are starting to work this week.This allows your little one to begin taking practice breaths. Baby could also be able to smell various sense in utero by this week too.if not that sense will kick in by the third trimester.</p>

			<p><b>Mother : </b>By 25 weeks pregnant your belly is getting bigger and heavier by each passing week and your baby inside is also growing day by day, second by second and also the baby is becoming very active and will start kicking and you might feel the kicks causing little discomfort and pain the baby will make you feel like you are literally "with your child."</p>
			<p>The pregnancy is associated with some discomforts,  enlarging uterus will press upon the internal organs, may cause gastritis, regurgitation of food, sleeplessness, difficulty in breathing, hemorrhoids, swellings in legs and frequent urination.</p>
			<p>Constipation can aggravate piles so you can prevent it by increasing the intake of fluid and fibre like fruits, vegetables and whole grains. Doing pelvic floor exercises and trying not to strain while defecation can help too.</p>
			<p>Your dental health now onwards is also very important because in pregnancy if there is untreated gingivitis it can progress to serious infections call periodontitis which is linked to premature birth and even increased risk of preeclampsia.</p>

			<p><b>Tips</b></p>
			<p><b>Use moisturizer : </b>because of enlarging uterus the skin over your belly stretches and may become itching there are chances that you may develop stretch marks so it's better to do gentle massage with moisturizer.</p>
			<p><b>note eye symptoms : </b>Your eyes are yet another seemingly random part of your body affected by hormones. During this time your vision might be less and your contact lenses might be less comfortable to wear. Even though your retaining fluid ironically your eyes maybe drier than ever. But don't worry eye symptoms like skin symptoms, will disappear after delivery .Be sure to let your practitioner no was going on so he or she can help you with.</p>
			<p><b>watch your BP : </b>Preeclampsia or arterial hypertension is a condition which may develop in pregnancy because of arterial spasms of the placenta. The clinical signs of it are very important and a lady can diagnose it at home. If she is gaining more wait more than 2 kg weight  in one week or if she's feeling severe pedal edema which pits on pressure or if she is suffering from headache and dizziness, right upper epigastrium pain, blurring of vision. These all are known as warning signs of preeclampsia and a lady should visit hospital at the earliest if any one of them is appreciable. The doctor will check your BP and will do urine test if needed and if this comes to be positive you will be started on some antihypertensive medications which is necessary to take on time and should not be stopped without doctors advice.</p>
		</div>
  </div>

  @endsection
