@extends('Apphtml.Trimster.main')
@section('title', 'Whta to expect second')
@section('content')


  <div class="container">
  	<div class="main" id="w1">
		<p>The second trimester of your pregnancy is from week 13 to week 28, or months 4, 5, and 6. It’s the middle phase of pregnancy, when you may start to see your “baby bump” and feel your baby’s movement for the first time.</p>
		<p>As you get into your second trimester of pregnancy, the morning sickness and fatigue you may have felt during the last 3 months should subside.</p>
		<p>The second trimester is, for many women, the easiest 3 months of pregnancy. Take the time now, while you're feeling better and your energy is up, to start planning for your baby's arrival. Get that nesting instinct on the drive!</p>
		<p>During the second trimester, your baby is growing quickly. Between your 18th and 22nd week of pregnancy you'll have a sonography so your doctor can see how your baby is growing. </p>
		<p>Although you should be feeling better now, big changes are still taking place inside your body. Here's what you can expect.</p>
		<p><b>Changes in Your Body</b></p>
		<p>Lower Abdominal pain: In your second trimester, you may feel some cramps or pain in your lower abdomen. Pain happen because as your uterus expands during pregnancy, it puts pressure on nearby muscles.</p>
		<p>Braxton-Hicks contractions. You may start to feel the muscles in your uterus tighten for a minute or two during the second trimester. These aren’t real contractions or signs of labor, but a normal symptom. They may come and go at random, and may feel irregular in their rhythm and strength. These muscle contractions often cause discomfort more than pain. Sex, intense exercise, dehydration, a full bladder, or even someone touching your baby bump can trigger Braxton-Hicks contractions. You can use these contractions to practice your breathing techniques for labor. To help yourself relax, take a warm bath, sip some warm herbal tea, change your body’s position, or drink more water.</p>
		<p>Breast changes. Much of the breast tenderness you experienced during the first trimester should be fading, but your breasts are still growing as they prepare to feed your baby. Going up a bra size (or more) and wearing a good support bra can make you feel more comfortable.</p>
		<p>Congestion and nose bleeds(epistaxis). Hormonal changes cause the mucus membranes of your nose to swell, which can lead to a stuffy nose and make you snore at night. These changes may also make your nose bleed more easily. Before using nasal decongestant, check with your doctor. Saline drops and other natural methods are safer ways to clear congestion during pregnancy. You can also try using a steam to keep the nasal mucosa moist. To stop a nosebleed, keep your head up straight (don't tilt it back) and apply pressure to the nostril for a few minutes until the bleeding stops.</p>
		<p>Discharge. It's normal to see a thin, milky white vaginal discharge (called leukorrhea) early in your pregnancy. You can wear a panty liner if it makes you feel more comfortable, but don't use a tampon because it can introduce germs into the vagina. If the discharge is foul smelling, green or yellow, bloody, or if there's a lot of clear discharge, call your doctor.</p>
		<p>Dizziness. As your uterus expands during the second trimester, it presses upon major blood vessels and causes you to feel dizzy at times. Other causes are low blood sugar or hormone changes during pregnancy. Try not to stand for too long. Rise slowly from chairs or bed. Eat regular meals. Wear loose clothes, avoid hot showers or baths, and try not to lie flat on your back for the rest of your pregnancy.</p>
		<p>Frequent micturition. Your uterus will grow beyond the pelvic cavity during the second trimester, giving you a brief break from having to keep going to the bathroom. Don't get too comfortable, though. The urge to go will come back during the last trimester of your pregnancy.</p>
		<p>Effect on hair. Pregnancy hormones can boost hair growth -- and not always where you want it. The hair on your head will become thicker. You may also be seeing hair in places you never had it before, including your face, arms, and back. Shaving and plucking might not be the easiest options, but they're probably your safest bets right now. Many experts don't recommend laser hair removal, electrolysis, waxing, or depilatories during pregnancy, because research still hasn't proven that they are safe for the baby. </p>
		<p>Headache are one of the most common pregnancy complaints. Try to get plenty of rest, and practice relaxation techniques, such as deep breathing. Aspirin and ibuprofen shouldn’t be taken during pregnancy, but your doctor may say it's OK for you to take acetaminophen (paracetamol) if you're really uncomfortable.</p>
		<p>Heartburn and constipation. These are due to your body making more of a hormone called progesterone. This hormone relaxes certain muscles, including the sphincter in your lower esophagus that normally keeps food and acids down in your stomach, and the ones that move digested food through your intestines. To relieve heartburn, try eating more frequent, smaller meals throughout the day and avoid greasy, spicy, and acidic foods (such as citrus fruits). For constipation, get more fiber and drink extra fluids to keep things moving more smoothly. Physical activity will also help move things along.</p>
		<p>Leg cramps. You may feel muscles in your legs contract and cramp during the second trimester. This often happens at night. It’s unclear what causes them. To prevent cramps, try to stretch your leg muscles before you go to bed, get regular exercise, eat foods rich in magnesium like beans or whole grains, drink plenty of fluids, get the recommended amount of calcium, and wear comfy shoes. To ease a bout of leg cramps, stretching, ice, heat, or massage may help.</p>
		<p>Quickening. By the midpoint of your pregnancy (20 weeks) you will probably have started to feel the first delicate flutters of movement in your abdomen, which is often called "quickening." If you aren't feeling your baby move yet, don't worry. Some women don't experience quickening until their sixth month of pregnancy.</p>
		<p>Skin changes. Pregnant women often look as though they are "glowing" because changing hormone levels make the skin on the face appear flushed. An increase in the pigment melanin can also lead to brown marks on the face (often called the "mask of pregnancy") and a dark line (linea nigra) down the middle of the abdomen. All of these skin changes should fade after the baby is born. In the meantime, you can use makeup to conceal them. Your skin is also more sensitive to the sun right now, so make sure to wear a broad-spectrum (UVA/UVB protection) sunscreen with an SPF of at least 30 whenever you go outside. Limit your time in the sun, especially between 10 a.m. and 2 p.m., wearing long-sleeved clothes, pants, a broad-brimmed hat, and sunglasses. You may also notice thin, reddish-purple lines on your abdomen, breasts, or thighs. These stretch marks emerge as your skin expands to accommodate your growing belly. Although many creams and lotions claim to prevent or eliminate stretch marks, there is little evidence that they actually do. Using a moisturizer can help soften your skin and reduce itchiness. Most stretch marks should fade on their own after you deliver.</p>
		<p>Spider naevi and varicose veins. Your circulation has increased to send extra blood to your growing baby. That excess blood flow can cause tiny red veins, known as spider veins, to appear on your skin. These veins should eventually fade once your baby is born. Pressure on your legs from your growing baby can also slow blood flow to your lower body, causing the veins in your legs to become swollen and blue or purple. These are called varicose veins. Although there's no way to avoid varicose veins, you can prevent them from getting worse by getting up and moving throughout the day and lifting up your legs on a stool whenever you have to sit for long periods of time. Wear support hose for extra support. Varicose veins should improve within 3 months after you deliver.</p>
		<p>Urinary tract infections. Bacterial infections in your urinary tract or bladder, which sits on top of your uterus, are common in the second trimester. They’re caused by changes in your urinary tract or your growing uterus making it harder to empty your bladder. You may have symptoms like pain or burning when you pee, a frequent urge to pee, cloudy or smelly urine, pain during sex, lower belly pain, or traces of blood or mucus in your urine. Bladder infections can spread to your kidneys and cause early labor or low-weight babies, so see your doctor right away. They’ll give you a urinalysis and urine culture to diagnose the infection, and prescribe antibiotics to treat it.</p>
		<p>Weight gain.Morning sickness usually subsides by the end of the first trimester. After that, your appetite should return to normal, and will probably grow. Although food is looking much more appetizing, be aware of how much you're eating. You only need about an extra 300 to 500 calories a day during the second trimester.</p>

		<p><b>Emergency Symptoms</b></p>
		<p>Any of these symptoms could be a sign that something is wrong with your pregnancy. Don't wait for your prenatal visit to talk about it. Call your doctor right away if you experience:</p>
			<ul><li>severe abdominal pain or cramping</li>
	        <li> Bleeding</li>
	        <li> Severe dizziness</li>
	        <li>Rapid weight gain (more than 5kg per month) or too little weight gain </li>
	        <li> Jaundice</li>
	        <li>Vomiting</li>
	        <li>A lot of sweating</li></ul>
	</div>
  </div>

@endsection
