@extends('Apphtml.Trimster.main')
@section('title', 'Weeks 31-35')
@section('content')
	<center>
      <div class="button-box">
	  	<!-- <div id="btn"></div> -->
        <button type="button" style="background-color:#FFFFFF; " class="toggle-btn button-box1" id="week11" onclick="week1()"><b>31</b></button>
        <button type="button" style="background-color:#40BECC; " class="toggle-btn button-box2" id="week12" onclick="week2()"><b>32</b></button>
        <button type="button" style="background-color:#40BECC; " class="toggle-btn button-box2" id="week13" onclick="week3()"><b>33</b></button>
        <button type="button" style="background-color:#40BECC; " class="toggle-btn button-box2" id="week14" onclick="week4()"><b>34</b></button>
        <button type="button" style="background-color:#40BECC; " class="toggle-btn button-box2" id="week15" onclick="week5()"><b>35</b></button>
  	  </div>
    </center>
  <div class="container">
  		<div id="w1"> 
  		</div>
			<h4>Week 31</h4>	
			<p><b>Baby :</b> The baby has well established sleep cycles. He is also putting in longest stretches of sleep, which is why you are probably noticing more defined pattern of wakefulness, movement and rest. The baby knows exactly when he is  awake and when he is sleeping. The sleep is divided into  two phases, active phase and deep phase. When the baby is in active state of sleep baby actually starts dreaming, it can be seen as the eyelids flutter, the eyeballs move . The brain keeps on developing between 31 to 32 weeks. The regions of brain carve out. The regions are allocated that which region of the brain will be responsible for which control of the body.</p>
			<p>The pigment continues to deposit in IRIS and hairs. The colour of iris is not decided till the baby is born. </p>
			<p>The internal organs are almost developed. They start functioning as well like the lungs start producing surfactant, the liver has started clearing the toxins but they still need the last month to become fully ready to function once the baby is outside the womb.</p>
			<p>Your baby's brain is working overtime this days developing faster than ever. Connections between individual nerve cells are being made at the superfast rate he is now processing information, tracking light and perceiving signals from all five senses. Surely your baby will not be able to smell anything right now but that's only because his still submerged in amniotic fluid and needs to be breathing air to get a whiff of anything.</p>
			<p><b>Mother :</b> So your stomach feels like it's in your chest and your lungs feel like....hmmm... they don't even feel like they are there anymore. do they ? Moving on up to 31 weeks pregnant, your uterus can be felt 4 inches above your navel. This means your uterus is pushing all the internal organs that used to be there somewhere else, crowding your diaphragm and the lungs and making it more difficult for them to expand. The result: your body is spare on air and will be until your baby drops near the end of pregnancy. While the shortness of breath may feel very uncomfortable to you, your baby is as happy as a calm because he is getting his oxygen from the placenta. Be sure to stand as straight as you can given the weight you are carrying around, eat smaller evenly spaced meals and sleep propped up on  your left side so that your lungs have more space to breathe.</p>
			<p>Now you will be keep on gaining weight about 50 grams a day or 200 to 300 grams a week. Don't overfeed yourself now. You have to keep a check on your weight because when you will overfeed, your baby is also overfed and giving birth to a heavyweight baby can  turn out to be a little difficult!</p>
			<p><b>Tips </b></p>
			<p><b>be safe while driving! : </b>while you start shopping for your baby please make sure that you don't jump over the bumps. It may lead to a preterm labor.</p>
			<p><b>watch your face! : </b>If you end up having sudden facial swelling do not considere it as normal for pregnancy but go and consult your doctor. Get your urine checked, get your blood pressure monitored, if the swelling is with headache ,confusion, dizziness, blurring of vision, upper epigastric pain or with a sense of uneasiness in the body they are the warning signs of preeclampsia.</p>
			<p><b>drink plenty of water! : </b>in case you haven't noticed,  the heats on when you are expecting, especially as you get bigger and bigger. But water keeps the body's cooling system running smoothly, even when you are inner a thermostats on high, buy dispersing excess heat in the form of sweat.</p>
			<p>Plus , an ample flow of fluids keeps pregnancy fatigue in check. One of the first symptoms of dehydration is exhaustion  and headaches at bay.</p>

		<div id="w2"> 
		</div>

			<h4>Week 32</h4>
			<p><b>Baby : </b>32 weeks pregnant you are likely feeling tapping and squirming instead of your baby's signature rocking and rolling. That's because while comfy your baby is a bit tight for exercise space right now - he is actually  in a curled up position. Between 32 and 38 weeks your baby will probably settle into the head down - bottoms up presentation in your pelvis in preparation for birth. That's because the foetus head fits better at the bottom of your inverted pear shaped uterus plus it's easier during childbirth if baby comes out head first. Fewer than 5% of babies prefer bottom down position by full-term.</p>
			<p>Baby's sleep cycle is very differentiable now and he actually sleeps in your room like the one who sleeps beside you. The sleep and wake cycles are following a regular rhythm by now.</p>
			<p>By 32 weeks baby grows by 200 to 250 grams in a week. The lungs are still developing and maturing. they started preparing for the respiration which is visible as ribs movement in sonography. The baby is not completely independent at this stage for his survival but if the baby is to come at this stage with good neonatal intensive care facilities the survival rate is good.</p>
			<p>The placenta is the basic structure which is providing nourishment to the foetus and the aging of placenta or the maturity of placenta can be noted on sonography as calcified dark spots in placenta. As long as it doesn't compromise the blood supply of the foetus it is considered normal.</p>
			<p>Babies bones are also growing as the internal organs. The length of long bones become long, the bones become more denser but the skull still remains maleable and this is necessary to aid in the journey of baby from mother's pelvis this will allow the head to negotiate through the narrow pelvic cavity.</p>
			<p>the baby's skin is now getting thicker and denser and blood vessels are not easily visible visible the vernix caseosa now disappears and also the lenugo start shading of the Lenovo on the scalp is replaced by soft hairs.</p>

			<p><b>Mother : </b>This week your body may start preparing for delivery by flexing its muscles literally if you feel your uterus is tightening or hardening periodically, those are Braxton Hicks contractions - irregular practice contractions that our first felt around with pregnancy and increase in frequency and strength as things progress.</p>
			<p>These are pre labor  rehearsals or warm up for the real thing and are typically experienced earlier and with more intensity in women who have been pregnant before, in fact many novice moms  to be don't notice them as much.</p>
			<p>How do you know they aren't real labour? They stop if you change position, so try getting up if you are lying down or walking if you have been sitting. If they are real labour contractions they will become progressively stronger and more regular in that case you should visit the hospital.</p>
			<p>During this time your nesting Instinct will be kicked. You will feel to do up your room and cupboards and make ready a room for your little one. If it brings joy to you you can do that.</p>
			<p>From 32 weeks onwards you have to keep a count of your baby's movement. Minimum the baby should move for 10 to 12 times in a day.</p>

			<p><b>Tips</b></p>
			<p><b>Write down your dreams : </b>Your night visions are extra trippy this days, thanks to pregnancy hormones. Many mums find pregnancy dreams and their dreams peak during the third trimester as sleep is more disrupted and they increasingly find themselves imagining what life with the new baby will be.</p>
			<p><b>don't stress over stretch marks : </b>Try not to obsess over stretch marks. It is estimated that 90% of women get it, plus they are a sign of your baby growing.</p>
			<p><b>learn early signs of labour : </b>learn the signs of preterm labour just in case water breaking, period like cramps , vaginal bleeding or spotting, a constant dull back ache, diarrhoea and a tightening feeling in your uterus.</p>
			<p>Decreased appetite With your big uterus crowding your insides, your appetite may be waning. Try to eat regular small snacks like a bite of Banana instead of bog meals.</p>
			<p>Do pelvic tilts your pelvis is crucial to a smooth pregnancy and delivery so treat it well one way to strengthen your pelvis is to do a regular pelvic tilt these easy exercises which you can do anywhere strengthen your abs soothe your back aches during pregnancy and labour and delivery.</p>

		<div id="w3"> 
		</div>

			<h4>Week 33</h4>
			<p><b>Baby : </b>By 33 weeks the baby is not full term yet, but if the destiny decides the early arrival of the baby then with special care taken during the process of labor and immediate admission to neonatal care unit most of the babies can survive. By 33 weeks all the development of organs is complete but the operational parameters are still developing, for example, the brain is structurally formed and is complete but the neuronal synapses which are still developing will keep on developing till few months after birth. The centres of control of limb movement, sensory perceptions are there but more finer  control like control of breathing, circulation it is still in developung and that is the reason why the babies need and NICU admission. The function of the body in last month is to gain weight and complete the functional development of internal organs and functional integrity of their coordinated work.</p>
			<p>The skin thickens and blood vessels are not that easily visible but the vernix and lanugo  now keep on shedding till it reaches the full term where the baby is completely clear of Lanugo.</p>
			<p>Also the lungs are still getting matured.the breathing exercise which a baby does is visible in ultrasound by the movement of ribs this, movement also helps heart to pump the blood.</p>
			<p>If your uterus had eyes, here's what you would see? at your fetus is acting more and more like a baby, with his eyes closing during sleep and opening while awake. And because those uterine walls  become thinner more and more light penetrates the womb helping your baby differentiate between day and night. Now if only baby can remember that difference on the outside.</p>
			<p>The baby's kick are getting stronger and it is more appreciated if it ends up getting your liver orbbladder.</p>
			<p>Your baby has reached an important milestone about now. He's got his own immune system. Antibodies are being passed from you to your little one as he continues to develop his fetal immune system. Which will come in handy once he is  outside the womb and fending off all sorts of germs.</p>

			<p><b>Mother : </b>Soon you will start a new life with a tiny human  besides your side. In this month of a pregnancy your body will feel a little more tired and you would like to take some good nap, but it is not an easy thing to do. Because the baby will continue to party in your womb while you want a good nap. And also because of the increasing size of the uterus the breathing becomes more difficult and you need to assume special recumbent position. Needing to go to bathroom now when again is a big headache. If by overcoming all these problems still if you are not able to have a sound sleep in night spare an hour in a day time to sleep. </p>
			<p>You might start feeling your face and body  in the last few months of pregnancy getting swollen up and it is completely normal to have swelling on your feet which you will observe mostly during night times and when you wake up your face might look puffy. Also in swelling of feet and face are signs of preeclampsia so it is advisable to once get it checked by your consultant. Other signs of preeclampsia are along with swelling there is pain in the right upper side of your abdomen with dizziness giddiness, severe headache and blurring of vision with a sense of an uneasiness in the body.</p>
			<p>With 33 weeks of pregnancy there is an increase in anxiety as well as nervousness and a sort of an excitement of the new arrival in the family but this period is very important for the consultant because now your baby needs a near vigilance so the follow up dates will be probably at 10 to 20 days apart with continuous monitoring of your fetal movement, fetal heart sound, baby's growth parameters the amount of amniotic fluid, the colour Doppler of umbilical cord, the maturation of placenta and in case if you have previous cesarean sections then the doctor will inspect the thickness of yours scar. They will confirm your expected date of the delivery and the mode of delivery is worked out during this period.</p>

			<p><b>Tips</b></p>
			<p><b>making a birth plan</b></p>
			<p><b>Have you heard that you can plan your delivery?</b></p>
			<p>yes you are hearing it right! this is the time when your baby is developing inside the womb to have a safe delivery and a grand welcome to the outside world but this is the exact time when a mother can ask the consultants what is the weight of the baby , how is the baby's growth , what would be the expected period of arrival of the baby , what is the mode of delivery, how a delivery will be conducted, whether the availability of painless delivery is there in your hospital or not , whether the baby  if needs  NICU support will it be provided in the hospital or not these all questions can be made out before the delivery so that it will prepare a mother to deliver the baby with full mental, physical and emotional preparation.</p>
			<p><b>Sneak in more calcium : </b>Milk taste sour in your mouth than there are plenty of ways to sneak your calcium. You can bland milk with smoothies for soups or bypass milk altogether and still cash in on calcium in the form of other dairy products. Most dairy products contain plenty particularly-  yoghurt as one cup has the same amount of calcium as a cup of milk and cheese.</p>
			<p><b>Switch to light weights : </b>Yes, weight training increases muscle tone and even prevent bone loss but during pregnancy its important to lighten up. Lifting heavy weights increases pressure in your body, this cause you to hold your breath and could compromise blood flow to the uterus plus losing ligaments could lead to injury.</p>
			<p><b>Prevent an upset stomach : </b>If your body has trouble producing enough lactase - the enzyme that breaks down the lactose in milk and encounter with dairy can lead to cramps gas bloating and diarrhoea. </p>
			<p>The good bacteria in yoghurt and some frozen yoghurt work to break down lactose so get active with those active yoghurt culture. Cut back on milk to it's possible to you can manage smaller amounts of dairy products. Try drinking only a half cup of milk at a time or nibbling on the thin slice of cheese.  Since lactose is easier to digest when mixed with other foods particularly high fibre was, once take a milk with whole grain cereal all melt that cheeze on a slice of a whole wheat bread or roti.</p>

		<div id="w4"> 
		</div>

			<h4>Week 34</h4>
			<p><b>Baby : </b>Not only thevmom's but your baby's body is too getting ready for the labor. The baby is now learning to control the movements of hands and legs. The baby is now started practicing respiration by swallowing of liquor. The sucking and grasp  reflexes are now clearly visible in sonography seen as moving the tongue inside out and trying to swallow the amniotic fluid.</p>
			<p> The grasping reflex can be seen by baby catching hold over the umbilical cord and playing with it.</p>
			<p>The babies glands like thyroid, thymus, adrenal glands, pituitary glands and many others start developing and become functional. The adrenal glands start secreting steroids which are necessary to initiate the milk reflex in the breast of the mother as well as the adrenal hormones are also needed to initiate the labor process.</p>
			<p> Babies digestive track is now also ready but yet not operational because most of the nutrients baby is still getting through the umbilical cord. Those tiny Little fingersnails have probably reached  the tips of his fingers by now and are getting ready for that first postpartum manicure. </p>
			<p>If your baby is a boy then this week the testicles are making their way down from the abdomen to the scrotum some full term baby boys roughly three to four percent are born with undescended testicles but they usually make the trip down some time before the first birthday about 30% of preterm boys are born with undescended testes too.</p>
			<p>It is said that by 34 completed weeks your Baby's lungs are now fully mature to breathe on its own so this is like crossing the  benchmark of your pregnancy, that is maturity of your foetus lungs, because that is what going to keep him alive independently.</p>

			<p><b>Mother : </b>Your eyes do not deceive you! Your uterus is still growing and you thought there was no more room and at 34 weeks pregnant it's almost a whole of a 5 inches above your navel now.</p>
			<p>Your vision changes!!  you are seeing things blurry!, that's because your eyes and yet another part of your body that can fall prey to those pesky pregnancy hormones. The same was doing a number on your digestive tract and your ligaments not only can your vision seem blurry these days but a decrease in production of tears can leave your eyes dry and irritated, especially if you wear contact lenses. What's more unsual is increase in fluid behind your eyes lens contemporary change their shape making some women more nearsighted or farsighted than usual. You may find wearing glasses rather than contact lenses to be more comfortable. Happily the changes are all temporary things should clear up as your eyes return to normal after delivery there is no need to change your prescription just yet! But to keep in mind that certain more serious vision problems can be a sign of preeclampsia so be sure to mention any vision changes to your practitioner.</p>
			<p>As you get closer to your labor, routine activities become more difficult, your gait is now shifted to a waddle gait, thanks to the hormones which are causing relaxation of your ligaments to aid the baby in the delivery. Also try being safe these days. Stop wearing High heels because the centre of gravity is now shifted. Don't take risky jobs like driving or climbing fastly on the stairs without holding the railings or not being careful on the bathrooms that might cause an event of slipping.</p>
			<p>Meanwhile as your uterus has reached its peak in the height, the breathing will become more difficult and you might need to change into a special position to breathe. Sleeping in recumbent position would be more comfortable then sleeping supine or by sleeping on turning on to one side.</p>
			<p>Unpleasant problems of heartburn and hemorrhoids may exacerbate during this period and try to avoid taking medicines  on your own rather consult your practitioner for the safer drugs that can be used during this time of pregnancy. To cross this benchmark is very essential for a mother because this is the time when you are preparing for the coming 9th month to deliver a healthy baby and your baby is also preparing inside the womb. This is really considered a Preterm stage which needs to be passed by every mother to deliver a healthy baby. You should take as much care of yourself in this period of time.</p>

			<p><b>Tips protect your eyes</b></p>
			<p>your eyes may be feeling more dry and sensitive than usual so keep your sunglasses and eye drops handy. Your eyes will be filled with tears of joy soon enough.</p>
			<p><b>get help for prenatal blues : </b>feeling blue? between 10 to 15% of pregnant women suffer from depression during pregnancy and its no wonder woman are even more susceptible to depression when they are expecting. Surging hormones coupled with stress, anxiety and societal pressure to feel a certain way can do a number on any woman's emotional state during pregnancy. Some factors can put you at greater risk for depression but it's an illness that strikes women of all ages and at all stages of their lives and there is no shame in asking for the help. Talk to your provider for some antidepressants that are safe to use when pregnant.</p>
			<p><b>Dont oversalt your food! : </b>Wondering if cutting back on the salt will help is the part that depends on how much salt you are eating in the first place! Doctor used to recommend a low sodium diet during pregnancy which really made satisfying those pickles and ice creams cravings a lot tougher- but thankfully they no longer do. A moderate amount of salt for example adding iodized table salt to your meals and eating lightly salted foods actually helps your body regulate fluid plus dramatically cutting back on sodium isn't good for the baby but before you to clear your pickle jar keep in mind that too much salt is the not good   for anyone, whether you are pregnant or not and it can even pump up the puffing.  The bottom lines -  salt but don't over salt your food give yourself one or two pickle per sitting limit, skip the heavily salted snacks and get in the habit of tasting before sprinkling.</p>
			<p><b>boost : </b>looking for an energy lift now that you have cut down on those coffees and teas? Believe it or not you will find it in regular exercise. A brisk walk, yoga or jog will increase blood flow and boost feel good endorphins since there is ulta vitalizing burst of energy. One that actually last longer than the coffee induce kind. need more convincing? Physical activities unlike those not is helps you sleep better to which will also help fight day time fatigue.</p>
			<p><b>sleep difficulties : </b>By this time sleeping becomes more difficult because of heart burns, breathing difficulties, unable to sleep by turning on one side, heightened emotional state and uncomfortable belly all this will come in the way of you having a good 7 to 8 hours of sleep.</p>
			<p>remember sleep is essential not only for mother but for the baby also because the hormones which are needed for growth and development of baby are produced more when you are at a calmer state. Try avoiding spicy food during late nights or late night munchings. Drink a glass of water when needed. go out in fresh air in night if u feel sleepless ness . Try listening soothing music and reading at night. Dont force your mind to sleep. It will sleep when it needs to.</p>

		<div id="w5"> 
		</div>

			<h4>Week 35</h4>			
			<p><b>Baby : </b>By 35th week of pregnancy baby is quite independent to live on his own. Baby has now gained more amount of subcutaneous fat and becomes more chubby. The cheeks and buttocks have round shape and creases start to appear. This skin smoothens now and becomes pinkish. The baby tries to suck and swallow more than usual during this period of time as the baby is practicing inhalation and exhalation.</p>
			<p>The baby blinks his eyes and gazes around, tilts its head. Though fetus chooses to sleep but know the foetus has become more of a human and emotions like fear joy are clearly reflected on his expressions and sometimes in a hard blown kick. Baby  immediately reacts to external irritants like noise, loud voice, bright lights.</p>
			<p>Baby's body is almost free of lenugo but some babies are still born with the furry look and the soft hairs are shed in first few weeks of life. The scalp is having soft hairs now. For most of the boys baby boy's the testicles has already descended in scrotum.</p>
			<p>Something else that's developing at the mind boggling pace this days -your baby's brain power. Luckily the part that surrounds that amazing brain - the skull remains soft and for good reasons soft skull will allow your baby to squeeze more easily through the birth canal.</p>

			<p><b>Mother : </b> At 35 weeks of pregnancy your uterus has reached the the highest benchmark possible and from now onwards it will sink down in your pelvis so that you will be able to breathe more easily. At 35 weeks of pregnancy your liquor is is at peak level and from 36 onwards it will go on decreasing. The placenta is mature and it will soon begin to age. Valcium will start getting deposited in the placenta which will be documented in your sonography as long as it doesn't compromise the vascular supply of the placenta the calcium deposit is  not considered harmful.</p>
			<p>By now you will start feeling Braxton Hicks contractions and they will keep on increasing this is the best time for you to prepare for your true labor by practicing the breathing exercise during this contractions these are irregular in their onset and will stay for very short period of time and will go away on its own.</p>
			<p>☐  Something else that will remind you just how far along you are in your pregnancy is frequent urination of course its first trimester's deja vu all over again but this time instead of pregnancy hormones to blame, is the position of your baby's head. Now that your baby is head down in preparation for delivery, he is pressing squarely on your bladder. As if that's not enough you may also experience urgency gotta- go now or a lack of bladder control when you cough, sneeze, or even laugh.</p>
			<p>Whatever you do you don't cut back on fluids. Instead empty your bladder as completely as possible by leaning forward just be careful not to tip over. Wear a pantyliner -if you need one and practice of Keigels exercise which will strengthen the pelvic muscles and prevent most cases of pregnancy induced incontinence.</p>
			<p><b>Tips</b></p>
			<p><b>research pain options : </b> These days there are a number of safe and effective medical options that can take some of the labor out of labor and delivery. You can probably go on searching the epidural anaesthesia and whether it is available in the institute or not, whether you are the right candidate to have that during your labor trial or not. This is the time when you can discuss the mode of delivery with your doctor.</p>
			<p><b>Stock up on nasal strips : </b> Because of the hormonal changes you may start snoring at this period so keep nasal strips  handy so that your sleep is not disturbed as well as the person who is sleeping  beside you.</p>
			<p><b>relieve heartburn : </b>Make sure  to sit up right while eating and stay that way for a couple of hours after you eat. Lying down, slouching, slumping and stooping will do you in. And when you have to bend do it with your knees instead of your waist otherwise you will send all that acid for a repeat ride up your esophagus. While you are eating do your body a favour and eat slowly. Chewing is the first step in the digestive process but it's the one that's most often neglected when eating's done the run. The more you chew the less work your stomach has to do.</p>
	</div>
</div>	
@endsection