@extends('Apphtml.Trimster.main')
@section('title', 'Weeks 35-40')
@section('content')
	<center>
      <div class="button-box">
	  	<!-- <div id="btn"></div> -->
        
        <button type="button" style="background-color:#FFFFFF; " class="toggle-btn button-box1" id="week11" onclick="week1()"><b>36</b></button>
        <button type="button" style="background-color:#40BECC; " class="toggle-btn button-box2" id="week12" onclick="week2()"><b>37</b></button>
        <button type="button" style="background-color:#40BECC; " class="toggle-btn button-box2" id="week13" onclick="week3()"><b>38</b></button>
        <button type="button" style="background-color:#40BECC; " class="toggle-btn button-box2" id="week14" onclick="week4()"><b>39</b></button>
        <button type="button" style="background-color:#40BECC; " class="toggle-btn button-box2" id="week15" onclick="week5()"><b>40</b></button>
  	  </div>
    </center>

  <div class="container">
  	
	<div id="w1"> 
	</div>
		<h4>Week 36</h4>
		<p><b>Baby : </b>Growth will slow down in coming weeks both so your baby will be able to fit through the narrow passage way to the outside and so he or she can store up all the energy needed for the delivery. By now your baby will at least make you realise 10 to 12 times a day that he is active not just by gentle movement inside your womb but by blow on your liver or ribs or bladder.</p>
		<p>When you are 36 weeks pregnant your baby skull bones are not fused together yet so the head can easily ( well relatively) easily maneuver through the birth canal. Your baby's skull is not the only soft structure in a little body. Most of a bones and cartilage are quite soft as well allowing for an easier journey into the world during delivery. But don't worry I will Harden for the first few years of a life.</p>
		<p>By now many of your baby systems are pretty mature, at least in baby terms and just about ready for life on the outside. Blood circulation for instance has been perfected and your baby's immune system has developed enough to protect your little one from infections outside the womb. Others however still need a few finishing touches. One such notable example is digestion which actually won't be fully mature until sometime after birth. Why? Inside her little gestational cucoon your baby has relied on the umbilical cord for nutrition meaning the digestive system though developed, hasn't been operational. It will take the first year or two to bring it up to the speed.</p>
		<p>in the preparation of labour babies adrenal gland turns on. It releases hormones  that causes the uterine contraction. It means baby decides for himself when to arrive in this world.</p>

		<p><b>Mother : </b> Welcome to your last month of pregnancy. It is a good thing your baby's is almost done cooking since your body me feel pretty done by now to. For one thing by 36 weeks pregnant you are doing the penguin waddle many third trimester mums to be adopt. The new walk is not in your imagination. It's in your connective tissue which those hormones are loosening and softening. And that's particularly important now that you are nearing your due date. You'r baby who is grown quite large by this point needs to fit through your pelvic bones so it's good that they are more flexible at this stage it's your body's way of getting ready to squeeze a big baby out of a small space.</p>
		<p>The downside to all this joint flexibility, besides the resemblance you now bear to your feathered friends, is pelvic pain. And the pressure from your baby's head but deeper and deeper in your pelvis in your heavier you trust weighing you down, and it's no wonder it's a pain to walk around these days. To relieve the discomfort, relax with your hips elevated, do some pelvic exercises, take warm baths, apply warm compress. Get a prenatal massage from certified therapist or try some complementary and alternative therapies. A belly sling may be helpful.</p>
		<p>There is a happy upshot, believe it or not. As a baby drops into your pelvic cavity - and keep in mind that not all baby drop before labor begins -  the upward pressure of uterus on your daiphragm is relieved. Once this lightning as it's known in the pregnancy strikes you will be able to take bigger and deeper breaths. Your stomach also won't be so squished anymore making eating a full meal more comfortable.</p>
		<p>Keep in mind the labour not always follows your ideal scenario. It's mandatory to have a positive mindset and flexibility for all the possible ways to deliver your healthy baby. Trust your doctor whatever decision they will take.</p>
		<p><b>Tips</b></p>
		<p><b>Note movement changes : </b>Don't be alarmed if your baby's movements have changed from  gentle moves to hard kicks. He has less room for the movements. You still keep track of your baby's movement everyday, do don't be stressed.  Try sipping a sugary beverage and see if your baby moves and be sure to call your doctor if there is any decrease in fetal movement or an unusual change in the pattern of baby's movement.</p>
		<p><b>Get plenty of B6 : </b>it's a good idea to change your protein with an adequate supply of pyridoxine it is known as vitamin b6 and it is very helpful and its function is to help your body and baby use all the protein to do this cell building job.</p>
		<p>You will find b6 in prenatal vitamins and also in bananas , brown rice ,bran ,Soya beans, oatmeals, potatoes, tomatoes, spinach, watermelon and meat. See there is overlap  in the protein source making a job even easier.</p>
		<p><b>Ask your pre labor signs : </b>If you feel uncomfortable and are concerned about any prelabour or pregnancy symptoms,  it's always best to call your healthcare provider. You might make a trip to hospital or doctors office that turns out to be unnecessary but you would be far far from the only mom-to-be who's done. So pre labor can last for a few hours or months or more and signs and symptoms can be different for every person.</p>
		<p><b>pack your hospital bag : </b>Delivery day is getting close to its time to pack your hospital bag if you haven't already.</p>

	<div id="w2"> 
	</div>

		<h4>Week 37</h4>
		<p><b>Baby : </b>By now your baby is fully grown to survive on its own. Usually by this time the baby acquires the position that is the head is lying just over the pelvis so that it can pass easily through birth canal. Technically before 37 completed weeks The baby is usually quoted as early term.</p>
		<p>The lungs are nature but not functional yet once the baby is delivered and take its first breath they will start functioning.</p>
		<p>The babies starts preparing for the first breath by simulating the inhaling and exhaling mechanism by drinking or swallowing the amniotic fluid. Part of it is filtered through urine and the remnants like hair, vernix, lanugo are are turned in the form of meconium.</p>
		<p>This meconium is thick like dark and it is excreted in first few weeks of birth. The babies are already having lactobacillus and E- coli which helps them to digest the mother's milk as well as boost their digestive immunity to prevent them from the infections.</p>
		<p>Some of the internal organs a are still developing like some neuronal layers of brain are still developing also the bones and cartilage starts to Harden except that of the skull bone. The wakefulness and sleep cycles are recognisable at this time in the baby and will remain so for few weeks after the birth.</p>
		<p><b>Mother : </b>At 37 weeks pregnant your baby's lungs are likely mature but that doesn't mean he's finished growing yet. In fact until the end of week 38 is technically considered an early term and he's  still packing on about 200grams per day or a kg a week. At this age the average foetus weighs about 2.5 kg.</p>
		<p>it's anyone's guess when your baby will decide to make his appearance will he be sociably early fashionably late or write on time but that doesn't stop your practitioner from guessing when labor will begin Just what is your doctor looking for first for dilutation or how far your cervix has opened specifically your service needs to open to 10 cm for the baby to pass through  the bird canal.</p>
		<p>There will be few noticeable changes in your body like your uterus riding down. More and More digestive upset and frequent urination because now uterus will create more pressure over your bladder and intestine  as it descends.</p>
		<p>Your breasts are also now preparing for lactation. You may start leaking colostrum, a thick yellow fluid from your breasts. Don't try to express the milk by pressing the nipples because it may elicit the labour due to release of oxytocin in your body. Just keep the breast clean and use nursing pads if needed.</p>
		<p>Right now your tiny  superstar is rehearsing for his big debut simulating breathing by inhaling and exhaling amniotic fluid, sucking his thumb blinking and pivoting from side to side. One day you feel his bottom on the left side the next its flipped around to the right!</p>
		<p><b>Tips</b></p>
		<p><b>finish your baby's nursery : </b>Less than 5% of babies deliver on the due date. So don't assume you have three weeks to finish your to do list but don't go crazy either.</p>
		<p><b>slow weight gain : </b>Not gaining a kg in a week is normal. Many women don't give any wet at all during the last month but the child keeps on growing.</p>
		<p><b>stay hydrated : </b>Feeling bloated don't stop drinking water drinking the recommended 8 glass will actually help ease your fluid retention.</p>
		<p><b>Get an exercise ball : </b>an exercise ball is safe and effective tool for strengthening your core muscles during pregnancy choose a high quality ball made from best resistant material and be short to inflate it to the correct size for your height. 22 inches (55 centimetres) for women shorter than 5 foot 3, and 26 inches (65 centimeters) tall women.</p>
		<p><b>stay sane while you rest : </b>Trying to establish a routine even if the highlight is a soak in a tepid tub, followed by a nap or a morning on the couch followed by an afternoon in the bed.</p>
		<p>You will feel a little better if you give the day some sort of structure and it's perfectly ok if your routine involves multiple viewings of your favourite show.</p>
		<p><b>choosing a labor support person : </b> Nowadays patients are given a choice to choose a person to support them in the labour process usually it is the person who will provide her with moral support and emotional support. Often the companion is husband or a mother or a friend. It is very important for the support person to be mentally strong and emotionally strong because if they will become anxious or nervous about the happenings going in the labour room they might create more tension that makes the doctor and the staff more uncomfortable.</p>

	<div id="w3"> 
	</div>

		<h4>Week 38</h4>
		<p><b>Baby : </b>Uour baby is good to go now! The growth now slows down as development and function of most of the organs in the body is almost complete but thanks to the subcutaneous fat it keeps on growing and the weight gain scale of baby goes on increasing. The muscle mass also increases and  it accounts for almost 25% of babies weight.</p>
		<p>The baby's skin is silky and Pinky. It continues to shed vernix and Lenugo. The sweat glands and oil glands in the skin are functional but the baby doesn't sweat for 3 to 4 weeks after birth because of the immaturity of the body heat regulation system. The lines, loops and whorls are now fully developed on the little finger tips of your child.</p>
		<p>The lungs are still maturing and producing more and more surfactant, a substance that prevents the air sacs in the lungs from sticking to each other once they start to breath.</p>
		<p>Your baby is also swallowing amniotic fluid- some of which winds up in her intestine where it along with other shed cells, bile and waste products turn into your baby's first bowel movement meconium and perhaps your first diaper change.</p>
		<p>Bone continues to grow and harden. the ear lobes now take their shape and all the folds in earlobe are clearly developed. The nails are fully grown and sometimes even extend beyond the fingertips.</p>
		<p>The reproductive organs of boy and girl are fully developed now and the hormones are produced in the body to cope with the stress of labor.</p>
		<p>Most other changes this week are small but important, they continue to add fat and fine-tune her brain and nervous system the way they can deal with all the stimulation that awaits them once they make entrance into the world.</p>

		<p><b>Mom : </b>This last few weeks you might feel better on breathing because your baby now descends into the pelvis and relaxes the pressure put on your internal organs and ribs. There is more comfortable breathing. You may feel heaviness in pelvis because of the descent of the baby. The uterus at sinks into the pelvis. The ligaments  softens and the pelvic cavity widens. In short your body now prepares for the big day.</p>
		<p>By now mothers might have experienced what is Braxton Hicks contraction. It may confuse you that are they the real contractions or the rehearsal ones?! The only difference between the real contraction and Braxton Hicks is that Braxton Hicks contractions are irregular ones and they subside on their own but the labor pain never subsides and interval keeps on decreasing at the intensity of pain keeps on increasing.</p>
		<p>Your baby is tightly held in the uterus and it sleeps more than usual during this time and the movement is decreased compared to previous because the baby is saving energy for the momentous event of arrival into the world.</p>
		<p>While you are waiting for your baby to arrive think of this last week as a dress rehearsal for life with your new arrival. Sleepless nights, a little anxiety and leaky breast. Yes it's true, many pregnant women find that they start leaking Colostrum from breast ,a thin yellowish liquid that's the precursor to breast milk sometime in third trimester. Its full of antibodies that protect your newborn it has more protein and less fat and sugar which is better for baby digestion then the milk.  Not all women experience it though. If not, no need to fret - your breasts are still producing colostrum for your baby when the time comes if you plan to breastfeed.</p>

		<p><b>tips</b></p>
		<p><b>prepare postpartum meals : </b>You should start preparing Indian snacks to stuff your pantry "dabbas" because those first few weeks or even months after the delivery cooking will be the last thing on your mind or your to do list because the baby will keep you so busy that you might end up eating unhealthy packaged foods. start making Indian snacks which are grandmothers and mothers are good at and stuff your pantry.</p>
		<p><b>double check your bag : </b>make sure the items in your hospital bag still fit you. baby cleaning wipes, diapers, 	extra pyjamas, your sanitary kit, multiple pairs of your undergarments this all should be ready in your bag.</p>
		<p><b>go for a walk : </b>daily routine of your walking will help your child to desend.</p>
		<p><b>research distractions : </b>Childbirth education programs generally rely on distraction to teach women to cope with their labour discomfort. Use whatever works best for you. Relaxation, Meditation and Visualisation techniques like imagining that your service. Cervix is opening your child is descending are often useful between contractions and breathing exercise can help during them some women are relaxed and preoccupied by music.</p>
		<p>Keeping your pain in perspective is also key to an easier labour. Staying rested, relaxed and positive will help you stay more comfortable. Tell yourself that the pain of a contraction is actually accomplishing something as each one of us gets you closer to your baby and remember it won't last forever.</p>
		<p><b>wear loose, cool clothing: </b>Perpetually damp this days? Here come those hormones again. Their effects, along with increased blood flow to the skin and increase metabolism during pregnancy can make you sweat more. To stay cool where loose light clothing drinking plenty of water and crack some windows or crank up the AC a sprinkle of talc free powder can also help absorb some moisture plus it can prevent a heat rash that could crop up underneath all that sweat.</p>
		<p><b>do squat exercises : </b>We all have heard tales of women squatting in the field to give birth. Well it turns out there's something to it. Squatting actually speed labour because it increases the pelvic opening providing more room for baby to descend.</p>
		<p><b>try labor inducing foods : </b>Unfortunately, at least as far as medical science is concerned (old wife is a different story), there is no miracle meal that will bring on the labor. In the category of "can't hurt might help" our foods such as brinjal ( eggplant), pineapple, papaya, seasome seeds laddu ,coffee ,chocolates. Whilr there is no proof that any of these are available in using qualities plenty of moms swear by them.</p>

	<div id="w4">
	</div>

		<h4>Week 39</h4>
		<p><b>baby : </b>Chubby cheeks, dimple chin, Rosy lips, NO teeth within. At 39 weeks pregnant I have got what is officially considered a full term baby.</p>
		<p>Those measurements won't change much from now but his brain is still growing at an astonishing rate - a pace that will continue for the first three years of life - with changes you will be able to recognise first and as your baby's skill packed bag of tricks expand almost daily.</p>
		<p>which 39 is for working  on sensory processing, reflexes and spinal column. two of the reflexes sucking and grasping reflexes are ready to go and dozen  more of of involuntary reflexes and conditioned responses will appear after birth.</p>
		<p>Their lungs are ready to expand and intestines are ready to function. The digestive tract is so well developed that it will be able to digest the highly nutritious collustrum from from now onwards</p>
		<p>Heard that babies cry a lot? there is definitely truth to that rumour - as you'll find out soon enough usually in the middle of the night but what you may not have heard that tiny babies don't produce tiny tears   when they cry since their tear ducts aren't fully open for business. </p>
		<p>Small babies have layers of fat around major vessels , internal organs and rib cage, this pad of fat helps them to regulate the body temperature. As the baby grows this set will slowly disappear.</p>

		<p><b>mother : </b>The end and a whole new beginning! - is inside at 39 weeks pregnant. You are probably feeling increasingly uncomfortable by now as you lug around your ever heavier uterus and its contents plus your pelvis is feeling achier and achier as your baby bears down. Braxton Hicks contractions are likely increasing in strength and frequency and that's a good sign since it means your body is gearing up for the big event. Finding a comfortable way to sit down or stand or lie down takes to go through several different positions. Mothers feel scared to sit down thinking that it might hurt the baby which is wrong, the pelvis protects the baby very well.</p>
		<p>Your appetite is changing now and small frequent meals which you use to take to avoid heartburn are no more needed as you feel more relaxed because your baby has now descended into your pelvis. You can eat your meal fully. Avoid eating baked foods, sweetsand heavy fried items.</p>
		<p>At 39 weeks you may find that you are dropping your weight by 1-2 kgs and that is because your body is preparing itself for the process of delivery by eliminating excesd water and anything else which may come into the way of labour. The hormones which initiate uterine contractions also have such effect on intestine and you will feel to purge.</p>
		<p>signs of Labor-Knowing that you can go any day you should be watching out for signs of labour. This include the rupture of the membranes or water breaking that contain amniotic fluid, diarrhoea or nausea which many women experience just before the onset of labour. spurts of energy also known as nesting Instinct, the loss of mucus plug that seals the opening of the uterus and bloody shaw which arise when your capillaries rupture from the dilatation and effacement of your cervix causing any discharge to appear pink or red tinged. Once you have seen bloody shaw labor is probably just a day or two away, so don't try to set your watch to it since it's not a definitive time table, just make sure your bags packed.</p>

		<p><b>Tips</b></p>
		<p><b>stages of labor : </b>For most of the women, labour is the most intense experience of their life. Being informed about the different stages of labor helps a woman to prepare their mind and strengthen their psychology and such women who are mentally prepared and psychologically strong are seen to have less difficulty during the course of natural labor pains.</p>
		<p><b>There are four stages of labor : </b>The first stage of labour is the beginning of contractions. These contractions are accompanied by dilatation and effacement of cervix and gradually when the contraction increases in frequency and duration the baby glides down the pelvis.</p>
		<p>The second stage of labour is from full dilatation of cervix till the delivery of your baby. In this stage the intensity of labour pain is much increased and becomes a sort of unbearable  intensity. Mother feels a natural urge to push down the baby these are known as bearing down efforts. Just as the baby is delivered there will be a sudden moment of relaxation felt by the mother. To make the most of it take a deep breath hold it in and try to push at the right place, don't push throug your face, legs and don't scream. Open up as much as possible and in between pushes  take a few deep breaths, relax and get recharge for the next big push.</p>
		<p>Finally your  baby emerges,  these few moments are giving a mother an unparalleled sense of euphoria. nurse will put the baby on your abdomen to have a skin to skin contact and the assistance staff or doctor will cut the umbilical cord. your baby will start crying now.</p>
		<p>the baby will be handed over to the pediatrician and now the  the third stage of labor begins.</p>
		<p>in this stage the doctor will deliver your placenta and will clean uterus of any after births . After giving you local anaesthesia your episiotomy stitches will be taken.</p>
		<p>In 4th stage of labour you will be under watchful eye that your blood pressure is maintaining you are not going through any unnecessary bleeding. Is your baby feeding well and the vaccination of your baby,  all these will be covered in this two hours after the birth.</p>
		<p>You should start feeding the baby within half an hour of birth because this will not only help the baby to get adapted to the new mechanism of procuring food but it will help to contract the uterus as well.</p>

	<div id="w5"> 
	</div>

		<h4>Week 40</h4>
		<p><b>Baby : </b> This is the moment you and your baby have been waiting for. At 40 weeks pregnant you are at official end of your pregnancy. Your baby probably ways anywhere between 2.2 to 2.8 to 3 kgs and measures between 19 to 22 inches. Hundreds of perfectly healthy babies are born smaller or bigger.</p>
		<p>your baby is as excited as ever to meet the outside world. His body and sense organs are now fully developed and in sonography your doctor might show you, that your baby is now playing inside your uterus with umbilical cord, holding it like a guitar or sucking his or her thumb. These all are his preparation or you can say rehearsal going in utero so that as soon as the baby is born the baby can latch to your breast and suck in the breast milk. The suckling and grasping reflex are present in your baby.</p>
		<p>Soon after birth the babies are very cranky because from the darkness and warmth of mothers womb,  the baby is suddenly into noisy and bright atmosphere. For him the outside atmosphere is hostile for a while so he will cry and let him cry that will indeed help his lung to expand.</p>
		<p>Also the first milk is often yellowish, thick and comes as few drops, it is known as colostrum. This colostrum is very rich in  antibodies and antitoxins. It prevents baby against infections as well as it helps digestive tract of baby to get adapted to the milk. It is produced in last few weeks of pregnancy and first few days after baby's birth every mother should feed the colostrum to the baby.</p>
		<p>From your baby's perspective you will look a bit blurry-- at birth baby Central vision is still developing. Its ok to say hello to your new arrival. Your baby will very likely recognise the sound of your voice and your partners .</p>
		<p>you will notice  that your little one is still curled in fetal position and that's because it's the only position she or he has really known. Its a comforting one to be in that's also why so many newborns like to be swaddled. It reminds them of your uterus. It will take some time for them to realise that they have room to spread out.</p>

		<p><b>mother : </b>Few more days of anxious waiting and the exciting and challenging time of labour is soon to start. when will your body know it's time to deliver this baby. Just because your due date is marked on a calendar doesn't mean mother nature's gotten the memo.</p>
 		<p>About 30% off all pregnancy last's longer than 40 weeks and it's anyone's guess when your might end. Thankfully your practitioner probably won't let it go longer than 41 weeks.By now you have no doubt lost a night or two's sleep over when and where it will happen.</p>
 		<p>One event that's not guaranteed before the onset of labour is your water breaking the rupture of amniotic sac surrounding your baby the last 9 months. first few more than 15% of women experience a rupture of membranes before liver begins and second if your water does break in public is less likely to come as a torrent shall tidal wave and more likely to come as a slow  circle or small gush. One thing you can be pretty sure of if your water breaks before your contractions have started labour will likely begin in earnest within 24 hours either that or your practitioner will start it for you within 24 hours.</p>
 		<p>Your water actually breaks when you are in labour either the cervix is fully dilated or cervix is not open that is premature rupture of membranes or else it will happen in first stage of labour. When yourwater break suddenly trying noticing the colour and order of it and the time of it and inform your practioner. If it's green ,brown or black you need to go to hospital immediately.</p>
 		<p>mucus plug that closes your cervix actually escapes out in the form of mucoid that is of egg white consistency, It may be mixed with blood giving it a colour of tan brown or pink or even sometimes red. Usually labour starts 2-3 days after expulsion of this mucus plug. It may come out while you are in toilet or taking bath or you might see it as a stain on your undergarments.</p>
 		<p><b>Tips, Ask about inducing the labour</b></p>
 		<p>talk to your practitioner about when, why and how he or she might want to induce the labour. Unless there are health and medical reasons to induce, it's typically not recommended before 40 completed weeks of pregnancy.</p>
 		<p><b>Shave safely : </b>feeling a little extra for furry these days? you can choose an option of waxing or shaving your legs and private parts but it is advisable to take help of some other person, because you might not be able to see beyond your belly and your balance might not be good. better to find a friend to do that for you.</p>
 		<p><b>Add iron : </b>In case you haven't heard labour takes endurance - and lots of it. To make sure you are the little labouring engine that could( and can) you will need to make sure your iron intake is up to the mark and iron deficiency can cause extra fatigue, something you don't want to take into the birthing room with you. Go on eating a little handful more of peas,  the green veggies iron fortified cereals, dry fruits, nuts and whole wheat bread and if you are eating non veg you can go for red meat. Eat your extra iron supplement which you should still be taking together with the vitamin c and calcium source for better absorption.</p>
 		<p><b>go for a soak! : </b> defy gravity and give your body a break from all the extra weight by floating in a warm bath or pool, avoid the hot tub though.!</p>
 		<p><b>do a mini workout! : </b>Turn from side to side, slowly twisting at the waist, letting your arm swing freely (being careful not to whack anyone). You can also clench your butt and hold for count of two then release. Try to do15 or 20 arm swings and but clenches-  it will make time pass and tone your muscles too.</p>
 		<p><b>keep busy : </b>Baby on the brain? it's hard to think of anything else when your due date has come near. Take a walk (which might even help get your contractions going), spend some time focusing on self care, you may not have the chance (once baby is on board). Watch a movie or two. Tell your friends and family to stop calling everyday, remind them that no news is  ......no news.</p>
 		<p><b>stay relaxed : </b>Of course you are as excited and nervous as can be, but it's important to try to relax atmost as you can during the first phase of labour will need to save your strength for later on.</p>
 		<p>You can also try taking a walk which might even kick up the contractions a notch.  eat little snake if your hungry but avoid fatty foods and don't overeat.</p>
 		<p> don't worry about obsessively timing contractions at this point will just get bored and frustrated but to check periodically to see whether there are getting closer together.</p>
 		<p> lastly make sure you use the bathroom as full bladder can get in the way of labour.</p>
  </div>
</div>

@endsection